openapi: 3.1.0
info:
  version: 1.0.0
  title: Contactbook
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    Contact Book API is a backend service that allows users to manage personal contact information securely.

    It includes full authentication and authorization functionality using Bearer access tokens,
    as well as a password reset flow via email.

   - 🔐 **Authentication**
      - User registration and login
      - Authentication via Bearer access token
      - Refresh tokens for prolonged sessions
      - Secure password reset via email with a JWT token
      - Password change functionality

    - 📇 **Contact Management**
      - Create, read, update, delete (CRUD) contacts
      - Each contact is user-specific and isolated per account
      - Search and filter contacts
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://hw2-mongodb-wh2g.onrender.com
paths:
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/send-reset-email.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/auth/reset-pwd.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    cookieAuth:
      type: apiKey
      in: cookie
      name: refreshToken
    sessionAuth:
      type: apiKey
      in: cookie
      name: sessionId
